'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("WengLee_Application.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property BOL() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("BOL", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property BOL_DOC() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("BOL_DOC", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property delete_enquiry() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("delete_enquiry", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Newtonsoft_Json() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Newtonsoft_Json", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pop_out_120() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pop-out-120", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Sales_Order() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Sales_Order", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Updater() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Updater", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to /* To prevent any potential data loss issues, you should review this script in detail before running it outside the context of the database designer.*/
        '''BEGIN TRANSACTION
        '''SET QUOTED_IDENTIFIER ON
        '''SET ARITHABORT ON
        '''SET NUMERIC_ROUNDABORT OFF
        '''SET CONCAT_NULL_YIELDS_NULL ON
        '''SET ANSI_NULLS ON
        '''SET ANSI_PADDING ON
        '''SET ANSI_WARNINGS ON
        '''COMMIT
        '''BEGIN TRANSACTION
        '''GO
        '''ALTER TABLE dbo.tblCustomer ADD
        '''	CustomerId_Link varchar(15) NULL
        '''GO
        '''ALTER TABLE dbo.tblCustomer SET (LOCK_ESCALATION = TABLE)
        '''GO
        '''COMMIT        ''' [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Version_13() As String
            Get
                Return ResourceManager.GetString("Version_13", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 
        '''CREATE TABLE [dbo].[tblInvoiceStatus](
        '''	[InvoiceNumber] [varchar](15) NULL,
        '''	[CustomerID] [varchar](15) NULL,
        '''	[Status] [varchar](150) NULL
        ''') ON [PRIMARY]
        '''
        '''
        '''INSERT INTO [dbWengLee].[dbo].[tblVersion]
        '''           ([Version])
        '''     VALUES
        '''           (14)
        '''           
        '''GO.
        '''</summary>
        Friend ReadOnly Property Version_14() As String
            Get
                Return ResourceManager.GetString("Version_14", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 
        '''CREATE TABLE [dbo].[tblProductSub](
        '''	[SubCatId] [int] NOT NULL,
        '''	[ProductId] [int] NULL,
        '''	[SubCatName] [varchar](250) NULL,
        '''	[CreatedBy] [int] NULL,
        '''	[CreatedDate] [datetime] NULL,
        ''' CONSTRAINT [PK_tblProductSub] PRIMARY KEY CLUSTERED 
        '''(
        '''	[SubCatId] ASC
        ''')WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
        ''') ON [PRIMARY]
        '''
        '''
        '''
        '''/* To prevent any potential data loss issues, you should review this script in detail b [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Version_15() As String
            Get
                Return ResourceManager.GetString("Version_15", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to /* To prevent any potential data loss issues, you should review this script in detail before running it outside the context of the database designer.*/
        '''BEGIN TRANSACTION
        '''SET QUOTED_IDENTIFIER ON
        '''SET ARITHABORT ON
        '''SET NUMERIC_ROUNDABORT OFF
        '''SET CONCAT_NULL_YIELDS_NULL ON
        '''SET ANSI_NULLS ON
        '''SET ANSI_PADDING ON
        '''SET ANSI_WARNINGS ON
        '''COMMIT
        '''BEGIN TRANSACTION
        '''GO
        '''ALTER TABLE dbo.tblSubStock ADD
        '''	T_Date datetime NULL
        '''GO
        '''ALTER TABLE dbo.tblSubStock SET (LOCK_ESCALATION = TABLE)
        '''GO
        '''COMMIT
        '''
        '''update tb [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Version_16() As String
            Get
                Return ResourceManager.GetString("Version_16", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ALTER TABLE dbo.tblProducts ADD
        '''	TrackInventory bit NULL
        '''
        '''	GO
        '''
        '''update tblProducts set TrackInventory = 1 
        '''
        '''
        '''
        '''
        '''INSERT INTO [dbWengLee].[dbo].[tblVersion]
        '''           ([Version])
        '''     VALUES
        '''           (17)
        '''           
        '''GO.
        '''</summary>
        Friend ReadOnly Property Version_17() As String
            Get
                Return ResourceManager.GetString("Version_17", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 
        '''
        '''
        '''
        '''INSERT INTO [dbWengLee].[dbo].[tblVersion]
        '''           ([Version])
        '''     VALUES
        '''           (18)
        '''           
        '''GO.
        '''</summary>
        Friend ReadOnly Property Version_18() As String
            Get
                Return ResourceManager.GetString("Version_18", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CREATE TABLE [dbo].[tblTask](
        '''	[TaskId] [int] NOT NULL,
        '''	[CreatedDate] [datetime] NULL,
        '''	[TaskDate] [datetime] NULL,
        '''	[Task] [nvarchar](max) NULL,
        '''	[TaskSubject] [nvarchar](500) NULL,
        '''	[Details] [nvarchar](max) NULL,
        '''	[Createdby] [int] NULL,
        '''	[UpdatedBy] [int] NULL,
        '''	[UpdatedDate] [datetime] NULL,
        '''	[TaskStatus] [varchar](50) NULL,
        ''' CONSTRAINT [PK_tblTask] PRIMARY KEY CLUSTERED 
        '''(
        '''	[TaskId] ASC
        ''')WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON,  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Version_19() As String
            Get
                Return ResourceManager.GetString("Version_19", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
